image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore
    init: dotnet tool restore && dotnet paket restore && dotnet build

vscode:
  extensions:
    - muhammad-sammy.csharp
    - ionide.ionide-fsharp
    - eamodio.gitlens
